# ai 配置

ai:
  driver: openai
  openai:
    default:
      api_key: ""
      base_url: https://api.openai.com/v1
      model: gpt-4o-mini
      prefix: ""
  ollama:
    default:
      host: http://127.0.0.1:11434
      model: llama3.1
      prefix: ""
