# database / redis 配置

database:
  orm:
    default: default
    migration:
      table: sys_migration
      dir: /migration
    connections:
      default:
        driver: mysql
        username: root
        password: ""
        host: 127.0.0.1
        port: "3306"
        db: upper
        charset: utf8mb4
        prefix: ""
        log_mode: error
        timeout: 3s
        read_timeout: 5s
        write_timeout: 5s
        pool:
          max_open_conns: 50
          max_idle_conns: 10
          conn_max_lifetime: 30m
          conn_max_idle_time: 5m
      report:
        driver: mysql
        username: root
        password: ""
        host: 127.0.0.1
        port: "3306"
        db: upper_report
        charset: utf8mb4
        prefix: rpt_
        log_mode: error
      postgres:
        driver: postgresql
        username: postgres
        password: ""
        host: 127.0.0.1
        port: "5432"
        db: upper
        sslmode: disable
        timezone: Asia/Shanghai
        prefix: ""
        log_mode: error
      sqlserver:
        driver: sqlserver
        username: sa
        password: ""
        host: 127.0.0.1
        port: "1433"
        db: upper
        prefix: ""
        log_mode: error
      sqlite:
        driver: sqlite
        path: /database/default.db

  redis:
    default: default
    connections:
      default:
        driver: redis
        host: 127.0.0.1
        port: "6379"
        username: ""
        password: ""
        db: 0
        log_mode: error
      cache:
        driver: redis
        host: 127.0.0.1
        port: "6379"
        username: ""
        password: ""
        db: 1
        log_mode: error
