# queue 配置

queue:
  default: default
  connections:
    default:
      driver: rabbitmq
      error: basic_error
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
      vhost: /
    report:
      driver: rabbitmq
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
      vhost: /
