# search 配置

search:
  driver: elasticsearch
  elasticsearch:
    default:
      host: http://127.0.0.1:9200
      hosts:
        - http://127.0.0.1:9200
      username: elastic
      password: changeme
      prefix: example_
  meilisearch:
    default:
      host: http://127.0.0.1:7700
      secret: masterKey
      prefix: example_
